=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module TalonOne
  # The properties specific to the \"addLoyaltyPoints\" effect. This gets triggered whenever a validated rule contained an \"add loyalty\" effect. These points are automatically stored and managed inside Talon.One. 
  class AddLoyaltyPointsEffectProps
    # The name / description of this loyalty point addition.
    attr_accessor :name

    # The ID of the loyalty program where these points were added.
    attr_accessor :program_id

    # The ID of the subledger within the loyalty program where these points were added.
    attr_accessor :sub_ledger_id

    # The amount of points that were added.
    attr_accessor :value

    # The original amount of loyalty points to be awarded.
    attr_accessor :desired_value

    # The user for whom these points were added.
    attr_accessor :recipient_integration_id

    # Date after which points will be valid.
    attr_accessor :start_date

    # Date after which points will expire.
    attr_accessor :expiry_date

    # The identifier of this addition in the loyalty ledger.
    attr_accessor :transaction_uuid

    # The index of the item in the cart items list on which the loyal points addition should be applied.
    attr_accessor :cart_item_position

    # For cart items with `quantity` > 1, the sub position indicates to which item the loyalty points addition is applied. 
    attr_accessor :cart_item_sub_position

    # The alphanumeric identifier of the loyalty card. 
    attr_accessor :card_identifier

    # The position of the bundle in a list of item bundles created from the same bundle definition.
    attr_accessor :bundle_index

    # The name of the bundle definition.
    attr_accessor :bundle_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'program_id' => :'programId',
        :'sub_ledger_id' => :'subLedgerId',
        :'value' => :'value',
        :'desired_value' => :'desiredValue',
        :'recipient_integration_id' => :'recipientIntegrationId',
        :'start_date' => :'startDate',
        :'expiry_date' => :'expiryDate',
        :'transaction_uuid' => :'transactionUUID',
        :'cart_item_position' => :'cartItemPosition',
        :'cart_item_sub_position' => :'cartItemSubPosition',
        :'card_identifier' => :'cardIdentifier',
        :'bundle_index' => :'bundleIndex',
        :'bundle_name' => :'bundleName'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'program_id' => :'Integer',
        :'sub_ledger_id' => :'String',
        :'value' => :'Float',
        :'desired_value' => :'Float',
        :'recipient_integration_id' => :'String',
        :'start_date' => :'DateTime',
        :'expiry_date' => :'DateTime',
        :'transaction_uuid' => :'String',
        :'cart_item_position' => :'Float',
        :'cart_item_sub_position' => :'Float',
        :'card_identifier' => :'String',
        :'bundle_index' => :'Integer',
        :'bundle_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::AddLoyaltyPointsEffectProps` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::AddLoyaltyPointsEffectProps`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'program_id')
        self.program_id = attributes[:'program_id']
      end

      if attributes.key?(:'sub_ledger_id')
        self.sub_ledger_id = attributes[:'sub_ledger_id']
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      end

      if attributes.key?(:'desired_value')
        self.desired_value = attributes[:'desired_value']
      end

      if attributes.key?(:'recipient_integration_id')
        self.recipient_integration_id = attributes[:'recipient_integration_id']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'expiry_date')
        self.expiry_date = attributes[:'expiry_date']
      end

      if attributes.key?(:'transaction_uuid')
        self.transaction_uuid = attributes[:'transaction_uuid']
      end

      if attributes.key?(:'cart_item_position')
        self.cart_item_position = attributes[:'cart_item_position']
      end

      if attributes.key?(:'cart_item_sub_position')
        self.cart_item_sub_position = attributes[:'cart_item_sub_position']
      end

      if attributes.key?(:'card_identifier')
        self.card_identifier = attributes[:'card_identifier']
      end

      if attributes.key?(:'bundle_index')
        self.bundle_index = attributes[:'bundle_index']
      end

      if attributes.key?(:'bundle_name')
        self.bundle_name = attributes[:'bundle_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @program_id.nil?
        invalid_properties.push('invalid value for "program_id", program_id cannot be nil.')
      end

      if @sub_ledger_id.nil?
        invalid_properties.push('invalid value for "sub_ledger_id", sub_ledger_id cannot be nil.')
      end

      if @value.nil?
        invalid_properties.push('invalid value for "value", value cannot be nil.')
      end

      if @recipient_integration_id.nil?
        invalid_properties.push('invalid value for "recipient_integration_id", recipient_integration_id cannot be nil.')
      end

      if @recipient_integration_id.to_s.length > 1000
        invalid_properties.push('invalid value for "recipient_integration_id", the character length must be smaller than or equal to 1000.')
      end

      if @transaction_uuid.nil?
        invalid_properties.push('invalid value for "transaction_uuid", transaction_uuid cannot be nil.')
      end

      if !@card_identifier.nil? && @card_identifier.to_s.length > 108
        invalid_properties.push('invalid value for "card_identifier", the character length must be smaller than or equal to 108.')
      end

      pattern = Regexp.new(/^[A-Za-z0-9_-]*$/)
      if !@card_identifier.nil? && @card_identifier !~ pattern
        invalid_properties.push("invalid value for \"card_identifier\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return false if @program_id.nil?
      return false if @sub_ledger_id.nil?
      return false if @value.nil?
      return false if @recipient_integration_id.nil?
      return false if @recipient_integration_id.to_s.length > 1000
      return false if @transaction_uuid.nil?
      return false if !@card_identifier.nil? && @card_identifier.to_s.length > 108
      return false if !@card_identifier.nil? && @card_identifier !~ Regexp.new(/^[A-Za-z0-9_-]*$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] recipient_integration_id Value to be assigned
    def recipient_integration_id=(recipient_integration_id)
      if recipient_integration_id.nil?
        fail ArgumentError, 'recipient_integration_id cannot be nil'
      end

      if recipient_integration_id.to_s.length > 1000
        fail ArgumentError, 'invalid value for "recipient_integration_id", the character length must be smaller than or equal to 1000.'
      end

      @recipient_integration_id = recipient_integration_id
    end

    # Custom attribute writer method with validation
    # @param [Object] card_identifier Value to be assigned
    def card_identifier=(card_identifier)
      if !card_identifier.nil? && card_identifier.to_s.length > 108
        fail ArgumentError, 'invalid value for "card_identifier", the character length must be smaller than or equal to 108.'
      end

      pattern = Regexp.new(/^[A-Za-z0-9_-]*$/)
      if !card_identifier.nil? && card_identifier !~ pattern
        fail ArgumentError, "invalid value for \"card_identifier\", must conform to the pattern #{pattern}."
      end

      @card_identifier = card_identifier
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          program_id == o.program_id &&
          sub_ledger_id == o.sub_ledger_id &&
          value == o.value &&
          desired_value == o.desired_value &&
          recipient_integration_id == o.recipient_integration_id &&
          start_date == o.start_date &&
          expiry_date == o.expiry_date &&
          transaction_uuid == o.transaction_uuid &&
          cart_item_position == o.cart_item_position &&
          cart_item_sub_position == o.cart_item_sub_position &&
          card_identifier == o.card_identifier &&
          bundle_index == o.bundle_index &&
          bundle_name == o.bundle_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, program_id, sub_ledger_id, value, desired_value, recipient_integration_id, start_date, expiry_date, transaction_uuid, cart_item_position, cart_item_sub_position, card_identifier, bundle_index, bundle_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TalonOne.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
