=begin
#Talon.One API

#The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'date'

module TalonOne
  class CartItemAdjustment
    # Loyalty Program to be used for payment
    attr_accessor :pay_from_loyalty_program

    # Amount of points to be spend
    attr_accessor :point_payment

    # Remaining price in currency after payment in points has been made
    attr_accessor :remaining_price

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pay_from_loyalty_program' => :'payFromLoyaltyProgram',
        :'point_payment' => :'pointPayment',
        :'remaining_price' => :'remainingPrice'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'pay_from_loyalty_program' => :'Integer',
        :'point_payment' => :'Integer',
        :'remaining_price' => :'Float'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'payFromLoyaltyProgram')
        self.pay_from_loyalty_program = attributes[:'payFromLoyaltyProgram']
      end

      if attributes.has_key?(:'pointPayment')
        self.point_payment = attributes[:'pointPayment']
      end

      if attributes.has_key?(:'remainingPrice')
        self.remaining_price = attributes[:'remainingPrice']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @pay_from_loyalty_program.nil?
        invalid_properties.push('invalid value for "pay_from_loyalty_program", pay_from_loyalty_program cannot be nil.')
      end

      if @point_payment.nil?
        invalid_properties.push('invalid value for "point_payment", point_payment cannot be nil.')
      end

      if @point_payment < 1
        invalid_properties.push('invalid value for "point_payment", must be greater than or equal to 1.')
      end

      if !@remaining_price.nil? && @remaining_price < 0
        invalid_properties.push('invalid value for "remaining_price", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @pay_from_loyalty_program.nil?
      return false if @point_payment.nil?
      return false if @point_payment < 1
      return false if !@remaining_price.nil? && @remaining_price < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] point_payment Value to be assigned
    def point_payment=(point_payment)
      if point_payment.nil?
        fail ArgumentError, 'point_payment cannot be nil'
      end

      if point_payment < 1
        fail ArgumentError, 'invalid value for "point_payment", must be greater than or equal to 1.'
      end

      @point_payment = point_payment
    end

    # Custom attribute writer method with validation
    # @param [Object] remaining_price Value to be assigned
    def remaining_price=(remaining_price)
      if !remaining_price.nil? && remaining_price < 0
        fail ArgumentError, 'invalid value for "remaining_price", must be greater than or equal to 0.'
      end

      @remaining_price = remaining_price
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pay_from_loyalty_program == o.pay_from_loyalty_program &&
          point_payment == o.point_payment &&
          remaining_price == o.remaining_price
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [pay_from_loyalty_program, point_payment, remaining_price].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TalonOne.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
