=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module TalonOne
  # A reward instance held by a customer profile.
  class CustomerProfileReward
    # The ID of the customer reward instance. A customer profile can have multiple instances of the same reward.
    attr_accessor :id

    # The integration ID of the customer reward instance.
    attr_accessor :integration_id

    # The ID of the reward this instance belongs to.
    attr_accessor :reward_id

    # The integration ID of the reward this instance belongs to.
    attr_accessor :reward_integration_id

    # The name of the reward.
    attr_accessor :reward_name

    # The customer-facing description of the reward.
    attr_accessor :description

    attr_accessor :rule

    # The status of the customer reward: - `unlocked`: The reward is available for use. - `used`: The reward has been used. 
    attr_accessor :status

    # The date and time when the reward was unlocked.
    attr_accessor :unlocked_at

    # The integration ID of the customer profile that unlocked the reward.   For rewards unlocked with a loyalty card, this can be any customer profile  linked to that loyalty card. 
    attr_accessor :unlocked_by_profile_integration_id

    # The date and time when the reward was used.
    attr_accessor :used_at

    # The integration ID of the customer profile that used the reward.   For rewards unlocked with a loyalty card, this can be any customer profile  linked to that loyalty card.   Only returned when the reward has been used. 
    attr_accessor :used_by_profile_integration_id

    # The ID of the loyalty program that the loyalty card belongs to. Only returned for rewards unlocked with a loyalty card.
    attr_accessor :loyalty_program_id

    # The identifier of the loyalty card, which must match the regular expression `^[A-Za-z0-9._%+@-]+$`. 
    attr_accessor :loyalty_card_identifier

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'integration_id' => :'integrationId',
        :'reward_id' => :'rewardId',
        :'reward_integration_id' => :'rewardIntegrationId',
        :'reward_name' => :'rewardName',
        :'description' => :'description',
        :'rule' => :'rule',
        :'status' => :'status',
        :'unlocked_at' => :'unlockedAt',
        :'unlocked_by_profile_integration_id' => :'unlockedByProfileIntegrationId',
        :'used_at' => :'usedAt',
        :'used_by_profile_integration_id' => :'usedByProfileIntegrationId',
        :'loyalty_program_id' => :'loyaltyProgramId',
        :'loyalty_card_identifier' => :'loyaltyCardIdentifier'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'integration_id' => :'String',
        :'reward_id' => :'Integer',
        :'reward_integration_id' => :'String',
        :'reward_name' => :'String',
        :'description' => :'String',
        :'rule' => :'RuleMetadata',
        :'status' => :'String',
        :'unlocked_at' => :'DateTime',
        :'unlocked_by_profile_integration_id' => :'String',
        :'used_at' => :'DateTime',
        :'used_by_profile_integration_id' => :'String',
        :'loyalty_program_id' => :'Integer',
        :'loyalty_card_identifier' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::CustomerProfileReward` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::CustomerProfileReward`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'integration_id')
        self.integration_id = attributes[:'integration_id']
      end

      if attributes.key?(:'reward_id')
        self.reward_id = attributes[:'reward_id']
      end

      if attributes.key?(:'reward_integration_id')
        self.reward_integration_id = attributes[:'reward_integration_id']
      end

      if attributes.key?(:'reward_name')
        self.reward_name = attributes[:'reward_name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'rule')
        self.rule = attributes[:'rule']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'unlocked_at')
        self.unlocked_at = attributes[:'unlocked_at']
      end

      if attributes.key?(:'unlocked_by_profile_integration_id')
        self.unlocked_by_profile_integration_id = attributes[:'unlocked_by_profile_integration_id']
      end

      if attributes.key?(:'used_at')
        self.used_at = attributes[:'used_at']
      end

      if attributes.key?(:'used_by_profile_integration_id')
        self.used_by_profile_integration_id = attributes[:'used_by_profile_integration_id']
      end

      if attributes.key?(:'loyalty_program_id')
        self.loyalty_program_id = attributes[:'loyalty_program_id']
      end

      if attributes.key?(:'loyalty_card_identifier')
        self.loyalty_card_identifier = attributes[:'loyalty_card_identifier']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @integration_id.nil?
        invalid_properties.push('invalid value for "integration_id", integration_id cannot be nil.')
      end

      if @reward_id.nil?
        invalid_properties.push('invalid value for "reward_id", reward_id cannot be nil.')
      end

      if @reward_integration_id.nil?
        invalid_properties.push('invalid value for "reward_integration_id", reward_integration_id cannot be nil.')
      end

      if @reward_name.nil?
        invalid_properties.push('invalid value for "reward_name", reward_name cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @unlocked_at.nil?
        invalid_properties.push('invalid value for "unlocked_at", unlocked_at cannot be nil.')
      end

      if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length > 108
        invalid_properties.push('invalid value for "loyalty_card_identifier", the character length must be smaller than or equal to 108.')
      end

      if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length < 4
        invalid_properties.push('invalid value for "loyalty_card_identifier", the character length must be great than or equal to 4.')
      end

      pattern = Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      if !@loyalty_card_identifier.nil? && @loyalty_card_identifier !~ pattern
        invalid_properties.push("invalid value for \"loyalty_card_identifier\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @integration_id.nil?
      return false if @reward_id.nil?
      return false if @reward_integration_id.nil?
      return false if @reward_name.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["unlocked", "used"])
      return false unless status_validator.valid?(@status)
      return false if @unlocked_at.nil?
      return false if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length > 108
      return false if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length < 4
      return false if !@loyalty_card_identifier.nil? && @loyalty_card_identifier !~ Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["unlocked", "used"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] loyalty_card_identifier Value to be assigned
    def loyalty_card_identifier=(loyalty_card_identifier)
      if !loyalty_card_identifier.nil? && loyalty_card_identifier.to_s.length > 108
        fail ArgumentError, 'invalid value for "loyalty_card_identifier", the character length must be smaller than or equal to 108.'
      end

      if !loyalty_card_identifier.nil? && loyalty_card_identifier.to_s.length < 4
        fail ArgumentError, 'invalid value for "loyalty_card_identifier", the character length must be great than or equal to 4.'
      end

      pattern = Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      if !loyalty_card_identifier.nil? && loyalty_card_identifier !~ pattern
        fail ArgumentError, "invalid value for \"loyalty_card_identifier\", must conform to the pattern #{pattern}."
      end

      @loyalty_card_identifier = loyalty_card_identifier
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          integration_id == o.integration_id &&
          reward_id == o.reward_id &&
          reward_integration_id == o.reward_integration_id &&
          reward_name == o.reward_name &&
          description == o.description &&
          rule == o.rule &&
          status == o.status &&
          unlocked_at == o.unlocked_at &&
          unlocked_by_profile_integration_id == o.unlocked_by_profile_integration_id &&
          used_at == o.used_at &&
          used_by_profile_integration_id == o.used_by_profile_integration_id &&
          loyalty_program_id == o.loyalty_program_id &&
          loyalty_card_identifier == o.loyalty_card_identifier
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, integration_id, reward_id, reward_integration_id, reward_name, description, rule, status, unlocked_at, unlocked_by_profile_integration_id, used_at, used_by_profile_integration_id, loyalty_program_id, loyalty_card_identifier].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TalonOne.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
