=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module TalonOne
  # The balance in a Loyalty Program for some Customer.
  class LedgerInfo
    # Sum of currently active points.
    attr_accessor :current_balance

    # Sum of pending points.
    attr_accessor :pending_balance

    # Sum of negative points. This implies that `currentBalance` is `0`.
    attr_accessor :negative_balance

    # **DEPRECATED** Value is shown as 0. 
    attr_accessor :expired_balance

    # **DEPRECATED** Value is shown as 0. 
    attr_accessor :spent_balance

    # The tentative points balance, reflecting the `currentBalance` and all point additions and deductions within the current open customer session. When the session is closed, the effects are applied and the `currentBalance` is updated to this value.  **Note:** Tentative balances are specific to the current session and do not take into account other open sessions for the given customer. 
    attr_accessor :tentative_current_balance

    # The tentative points balance, reflecting the `pendingBalance` and all point additions with a future activation date within the current open customer session. When the session is closed, the effects are applied and the `pendingBalance` is updated to this value.  **Note:** Tentative balances are specific to the current session and do not take into account other open sessions for the given customer. 
    attr_accessor :tentative_pending_balance

    # The tentative negative balance after all additions and deductions from the current customer session are applied to `negativeBalance`. When the session is closed, the tentative effects are applied and `negativeBalance` is updated to this value.  **Note:** Tentative balances are specific to the current session and do not take into account other open sessions for the given customer. 
    attr_accessor :tentative_negative_balance

    attr_accessor :current_tier

    # Points required to move up a tier.
    attr_accessor :points_to_next_tier

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'current_balance' => :'currentBalance',
        :'pending_balance' => :'pendingBalance',
        :'negative_balance' => :'negativeBalance',
        :'expired_balance' => :'expiredBalance',
        :'spent_balance' => :'spentBalance',
        :'tentative_current_balance' => :'tentativeCurrentBalance',
        :'tentative_pending_balance' => :'tentativePendingBalance',
        :'tentative_negative_balance' => :'tentativeNegativeBalance',
        :'current_tier' => :'currentTier',
        :'points_to_next_tier' => :'pointsToNextTier'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'current_balance' => :'Float',
        :'pending_balance' => :'Float',
        :'negative_balance' => :'Float',
        :'expired_balance' => :'Float',
        :'spent_balance' => :'Float',
        :'tentative_current_balance' => :'Float',
        :'tentative_pending_balance' => :'Float',
        :'tentative_negative_balance' => :'Float',
        :'current_tier' => :'Tier',
        :'points_to_next_tier' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::LedgerInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::LedgerInfo`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'current_balance')
        self.current_balance = attributes[:'current_balance']
      end

      if attributes.key?(:'pending_balance')
        self.pending_balance = attributes[:'pending_balance']
      end

      if attributes.key?(:'negative_balance')
        self.negative_balance = attributes[:'negative_balance']
      end

      if attributes.key?(:'expired_balance')
        self.expired_balance = attributes[:'expired_balance']
      end

      if attributes.key?(:'spent_balance')
        self.spent_balance = attributes[:'spent_balance']
      end

      if attributes.key?(:'tentative_current_balance')
        self.tentative_current_balance = attributes[:'tentative_current_balance']
      end

      if attributes.key?(:'tentative_pending_balance')
        self.tentative_pending_balance = attributes[:'tentative_pending_balance']
      end

      if attributes.key?(:'tentative_negative_balance')
        self.tentative_negative_balance = attributes[:'tentative_negative_balance']
      end

      if attributes.key?(:'current_tier')
        self.current_tier = attributes[:'current_tier']
      end

      if attributes.key?(:'points_to_next_tier')
        self.points_to_next_tier = attributes[:'points_to_next_tier']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @current_balance.nil?
        invalid_properties.push('invalid value for "current_balance", current_balance cannot be nil.')
      end

      if @pending_balance.nil?
        invalid_properties.push('invalid value for "pending_balance", pending_balance cannot be nil.')
      end

      if @expired_balance.nil?
        invalid_properties.push('invalid value for "expired_balance", expired_balance cannot be nil.')
      end

      if @spent_balance.nil?
        invalid_properties.push('invalid value for "spent_balance", spent_balance cannot be nil.')
      end

      if @tentative_current_balance.nil?
        invalid_properties.push('invalid value for "tentative_current_balance", tentative_current_balance cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @current_balance.nil?
      return false if @pending_balance.nil?
      return false if @expired_balance.nil?
      return false if @spent_balance.nil?
      return false if @tentative_current_balance.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          current_balance == o.current_balance &&
          pending_balance == o.pending_balance &&
          negative_balance == o.negative_balance &&
          expired_balance == o.expired_balance &&
          spent_balance == o.spent_balance &&
          tentative_current_balance == o.tentative_current_balance &&
          tentative_pending_balance == o.tentative_pending_balance &&
          tentative_negative_balance == o.tentative_negative_balance &&
          current_tier == o.current_tier &&
          points_to_next_tier == o.points_to_next_tier
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [current_balance, pending_balance, negative_balance, expired_balance, spent_balance, tentative_current_balance, tentative_pending_balance, tentative_negative_balance, current_tier, points_to_next_tier].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TalonOne.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
