=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module TalonOne
  # Details of a risk, including its most severely affected entities.
  class RiskDetail
    # The internal ID of this entity.
    attr_accessor :id

    # The time this entity was created.
    attr_accessor :created

    # The ID of the risk notification rule that flagged this risk.
    attr_accessor :notification_id

    # The date of the activity data in which this risk was detected. The anomaly detection pipeline scores complete 24-hour cycles, so this is always the day before the risk was reported, not the reporting date itself. 
    attr_accessor :feature_date

    # The Application group this risk was detected in. Contains the Application ID, or `__GLOBAL__` for metrics that are not grouped by Application. 
    attr_accessor :group_key

    # The ID of the Application this risk belongs to. Absent for global metrics.
    attr_accessor :application_id

    # The triage lifecycle status of this risk.
    attr_accessor :status

    # The critical classification bucket of this risk.
    attr_accessor :criticality

    # The entity type the risk was detected in.
    attr_accessor :entity

    # The activity metric the risk was detected in.
    attr_accessor :activity

    # The rolling time window of the risk evaluation.
    attr_accessor :time_frame

    # The time the ML service reported this risk.
    attr_accessor :reported_date

    # The total number of entities affected by this risk.
    attr_accessor :affected_entity_count

    # Human-readable description of the detected anomaly.
    attr_accessor :description

    # The reason this risk was discarded. Only present on discarded risks.
    attr_accessor :discard_reason

    # The free-text details of the latest reclassification action: the description for resolving confirmed risks, or the details for discarding risks. 
    attr_accessor :status_comment

    # The ID of the user who performed the latest reclassification action.
    attr_accessor :status_changed_by

    # The time of the latest reclassification action.
    attr_accessor :status_changed_at

    # Timestamp of the most recent update.
    attr_accessor :modified

    # The affected entities with the highest severity ratios, in descending order.
    attr_accessor :affected_entities

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'created' => :'created',
        :'notification_id' => :'notificationId',
        :'feature_date' => :'featureDate',
        :'group_key' => :'groupKey',
        :'application_id' => :'applicationId',
        :'status' => :'status',
        :'criticality' => :'criticality',
        :'entity' => :'entity',
        :'activity' => :'activity',
        :'time_frame' => :'timeFrame',
        :'reported_date' => :'reportedDate',
        :'affected_entity_count' => :'affectedEntityCount',
        :'description' => :'description',
        :'discard_reason' => :'discardReason',
        :'status_comment' => :'statusComment',
        :'status_changed_by' => :'statusChangedBy',
        :'status_changed_at' => :'statusChangedAt',
        :'modified' => :'modified',
        :'affected_entities' => :'affectedEntities'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'created' => :'DateTime',
        :'notification_id' => :'Integer',
        :'feature_date' => :'Date',
        :'group_key' => :'String',
        :'application_id' => :'Integer',
        :'status' => :'String',
        :'criticality' => :'String',
        :'entity' => :'String',
        :'activity' => :'String',
        :'time_frame' => :'String',
        :'reported_date' => :'DateTime',
        :'affected_entity_count' => :'Integer',
        :'description' => :'String',
        :'discard_reason' => :'String',
        :'status_comment' => :'String',
        :'status_changed_by' => :'Integer',
        :'status_changed_at' => :'DateTime',
        :'modified' => :'DateTime',
        :'affected_entities' => :'Array<RiskAffectedEntityItem>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::RiskDetail` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::RiskDetail`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'notification_id')
        self.notification_id = attributes[:'notification_id']
      end

      if attributes.key?(:'feature_date')
        self.feature_date = attributes[:'feature_date']
      end

      if attributes.key?(:'group_key')
        self.group_key = attributes[:'group_key']
      end

      if attributes.key?(:'application_id')
        self.application_id = attributes[:'application_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'criticality')
        self.criticality = attributes[:'criticality']
      end

      if attributes.key?(:'entity')
        self.entity = attributes[:'entity']
      end

      if attributes.key?(:'activity')
        self.activity = attributes[:'activity']
      end

      if attributes.key?(:'time_frame')
        self.time_frame = attributes[:'time_frame']
      end

      if attributes.key?(:'reported_date')
        self.reported_date = attributes[:'reported_date']
      end

      if attributes.key?(:'affected_entity_count')
        self.affected_entity_count = attributes[:'affected_entity_count']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'discard_reason')
        self.discard_reason = attributes[:'discard_reason']
      end

      if attributes.key?(:'status_comment')
        self.status_comment = attributes[:'status_comment']
      end

      if attributes.key?(:'status_changed_by')
        self.status_changed_by = attributes[:'status_changed_by']
      end

      if attributes.key?(:'status_changed_at')
        self.status_changed_at = attributes[:'status_changed_at']
      end

      if attributes.key?(:'modified')
        self.modified = attributes[:'modified']
      end

      if attributes.key?(:'affected_entities')
        if (value = attributes[:'affected_entities']).is_a?(Array)
          self.affected_entities = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @created.nil?
        invalid_properties.push('invalid value for "created", created cannot be nil.')
      end

      if @notification_id.nil?
        invalid_properties.push('invalid value for "notification_id", notification_id cannot be nil.')
      end

      if @feature_date.nil?
        invalid_properties.push('invalid value for "feature_date", feature_date cannot be nil.')
      end

      if @group_key.nil?
        invalid_properties.push('invalid value for "group_key", group_key cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @criticality.nil?
        invalid_properties.push('invalid value for "criticality", criticality cannot be nil.')
      end

      if @entity.nil?
        invalid_properties.push('invalid value for "entity", entity cannot be nil.')
      end

      if @activity.nil?
        invalid_properties.push('invalid value for "activity", activity cannot be nil.')
      end

      if @time_frame.nil?
        invalid_properties.push('invalid value for "time_frame", time_frame cannot be nil.')
      end

      if @reported_date.nil?
        invalid_properties.push('invalid value for "reported_date", reported_date cannot be nil.')
      end

      if @affected_entity_count.nil?
        invalid_properties.push('invalid value for "affected_entity_count", affected_entity_count cannot be nil.')
      end

      if @modified.nil?
        invalid_properties.push('invalid value for "modified", modified cannot be nil.')
      end

      if @affected_entities.nil?
        invalid_properties.push('invalid value for "affected_entities", affected_entities cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @created.nil?
      return false if @notification_id.nil?
      return false if @feature_date.nil?
      return false if @group_key.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["active", "in_review", "confirmed", "discarded"])
      return false unless status_validator.valid?(@status)
      return false if @criticality.nil?
      criticality_validator = EnumAttributeValidator.new('String', ["critical", "not_critical"])
      return false unless criticality_validator.valid?(@criticality)
      return false if @entity.nil?
      entity_validator = EnumAttributeValidator.new('String', ["customer_profile", "customer_session"])
      return false unless entity_validator.valid?(@entity)
      return false if @activity.nil?
      activity_validator = EnumAttributeValidator.new('String', ["loyalty_points_earned", "discounted_amount", "completed_orders", "coupon_attempts"])
      return false unless activity_validator.valid?(@activity)
      return false if @time_frame.nil?
      time_frame_validator = EnumAttributeValidator.new('String', ["1D", "7D", "30D"])
      return false unless time_frame_validator.valid?(@time_frame)
      return false if @reported_date.nil?
      return false if @affected_entity_count.nil?
      discard_reason_validator = EnumAttributeValidator.new('String', ["expected_behavior", "other"])
      return false unless discard_reason_validator.valid?(@discard_reason)
      return false if @modified.nil?
      return false if @affected_entities.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["active", "in_review", "confirmed", "discarded"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] criticality Object to be assigned
    def criticality=(criticality)
      validator = EnumAttributeValidator.new('String', ["critical", "not_critical"])
      unless validator.valid?(criticality)
        fail ArgumentError, "invalid value for \"criticality\", must be one of #{validator.allowable_values}."
      end
      @criticality = criticality
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] entity Object to be assigned
    def entity=(entity)
      validator = EnumAttributeValidator.new('String', ["customer_profile", "customer_session"])
      unless validator.valid?(entity)
        fail ArgumentError, "invalid value for \"entity\", must be one of #{validator.allowable_values}."
      end
      @entity = entity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] activity Object to be assigned
    def activity=(activity)
      validator = EnumAttributeValidator.new('String', ["loyalty_points_earned", "discounted_amount", "completed_orders", "coupon_attempts"])
      unless validator.valid?(activity)
        fail ArgumentError, "invalid value for \"activity\", must be one of #{validator.allowable_values}."
      end
      @activity = activity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] time_frame Object to be assigned
    def time_frame=(time_frame)
      validator = EnumAttributeValidator.new('String', ["1D", "7D", "30D"])
      unless validator.valid?(time_frame)
        fail ArgumentError, "invalid value for \"time_frame\", must be one of #{validator.allowable_values}."
      end
      @time_frame = time_frame
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] discard_reason Object to be assigned
    def discard_reason=(discard_reason)
      validator = EnumAttributeValidator.new('String', ["expected_behavior", "other"])
      unless validator.valid?(discard_reason)
        fail ArgumentError, "invalid value for \"discard_reason\", must be one of #{validator.allowable_values}."
      end
      @discard_reason = discard_reason
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          created == o.created &&
          notification_id == o.notification_id &&
          feature_date == o.feature_date &&
          group_key == o.group_key &&
          application_id == o.application_id &&
          status == o.status &&
          criticality == o.criticality &&
          entity == o.entity &&
          activity == o.activity &&
          time_frame == o.time_frame &&
          reported_date == o.reported_date &&
          affected_entity_count == o.affected_entity_count &&
          description == o.description &&
          discard_reason == o.discard_reason &&
          status_comment == o.status_comment &&
          status_changed_by == o.status_changed_by &&
          status_changed_at == o.status_changed_at &&
          modified == o.modified &&
          affected_entities == o.affected_entities
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, created, notification_id, feature_date, group_key, application_id, status, criticality, entity, activity, time_frame, reported_date, affected_entity_count, description, discard_reason, status_comment, status_changed_by, status_changed_at, modified, affected_entities].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TalonOne.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
