=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module TalonOne
  # The properties specific to the \"unlockReward\" effect. This gets triggered whenever a validated rule unlocks a reward for a customer profile.
  class UnlockRewardEffectProps
    # The integration ID assigned to the customer reward unlock.
    attr_accessor :integration_id

    # The internal ID of the reward that was unlocked.
    attr_accessor :reward_id

    # The internal ID of the application the reward belongs to.
    attr_accessor :application_id

    # The integration ID of the customer profile that unlocked the reward.
    attr_accessor :profile_integration_id

    # The time the reward was unlocked.
    attr_accessor :unlocked_at

    # The identifier of the loyalty card, which must match the regular expression `^[A-Za-z0-9._%+@-]+$`. 
    attr_accessor :card_identifier

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'integration_id' => :'integrationId',
        :'reward_id' => :'rewardId',
        :'application_id' => :'applicationId',
        :'profile_integration_id' => :'profileIntegrationId',
        :'unlocked_at' => :'unlockedAt',
        :'card_identifier' => :'cardIdentifier'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'integration_id' => :'String',
        :'reward_id' => :'Integer',
        :'application_id' => :'Integer',
        :'profile_integration_id' => :'String',
        :'unlocked_at' => :'DateTime',
        :'card_identifier' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::UnlockRewardEffectProps` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::UnlockRewardEffectProps`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'integration_id')
        self.integration_id = attributes[:'integration_id']
      end

      if attributes.key?(:'reward_id')
        self.reward_id = attributes[:'reward_id']
      end

      if attributes.key?(:'application_id')
        self.application_id = attributes[:'application_id']
      end

      if attributes.key?(:'profile_integration_id')
        self.profile_integration_id = attributes[:'profile_integration_id']
      end

      if attributes.key?(:'unlocked_at')
        self.unlocked_at = attributes[:'unlocked_at']
      end

      if attributes.key?(:'card_identifier')
        self.card_identifier = attributes[:'card_identifier']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @integration_id.nil?
        invalid_properties.push('invalid value for "integration_id", integration_id cannot be nil.')
      end

      if @reward_id.nil?
        invalid_properties.push('invalid value for "reward_id", reward_id cannot be nil.')
      end

      if @application_id.nil?
        invalid_properties.push('invalid value for "application_id", application_id cannot be nil.')
      end

      if @profile_integration_id.nil?
        invalid_properties.push('invalid value for "profile_integration_id", profile_integration_id cannot be nil.')
      end

      if @unlocked_at.nil?
        invalid_properties.push('invalid value for "unlocked_at", unlocked_at cannot be nil.')
      end

      if !@card_identifier.nil? && @card_identifier.to_s.length > 108
        invalid_properties.push('invalid value for "card_identifier", the character length must be smaller than or equal to 108.')
      end

      if !@card_identifier.nil? && @card_identifier.to_s.length < 4
        invalid_properties.push('invalid value for "card_identifier", the character length must be great than or equal to 4.')
      end

      pattern = Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      if !@card_identifier.nil? && @card_identifier !~ pattern
        invalid_properties.push("invalid value for \"card_identifier\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @integration_id.nil?
      return false if @reward_id.nil?
      return false if @application_id.nil?
      return false if @profile_integration_id.nil?
      return false if @unlocked_at.nil?
      return false if !@card_identifier.nil? && @card_identifier.to_s.length > 108
      return false if !@card_identifier.nil? && @card_identifier.to_s.length < 4
      return false if !@card_identifier.nil? && @card_identifier !~ Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] card_identifier Value to be assigned
    def card_identifier=(card_identifier)
      if !card_identifier.nil? && card_identifier.to_s.length > 108
        fail ArgumentError, 'invalid value for "card_identifier", the character length must be smaller than or equal to 108.'
      end

      if !card_identifier.nil? && card_identifier.to_s.length < 4
        fail ArgumentError, 'invalid value for "card_identifier", the character length must be great than or equal to 4.'
      end

      pattern = Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      if !card_identifier.nil? && card_identifier !~ pattern
        fail ArgumentError, "invalid value for \"card_identifier\", must conform to the pattern #{pattern}."
      end

      @card_identifier = card_identifier
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          integration_id == o.integration_id &&
          reward_id == o.reward_id &&
          application_id == o.application_id &&
          profile_integration_id == o.profile_integration_id &&
          unlocked_at == o.unlocked_at &&
          card_identifier == o.card_identifier
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [integration_id, reward_id, application_id, profile_integration_id, unlocked_at, card_identifier].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TalonOne.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
